export const newsCategories = [
    "All",
    "Finance",
    "HR",
    "IT",
    "Culture",
    "HSE",
    "Facilities",
];

export const typeColors = {
    GRASS: { bg: "bg-green-600", text: "text-white" },
    WATER: { bg: "bg-blue-500", text: "text-white" },
    ELECTRIC: { bg: "bg-yellow-400", text: "text-gray-900" },
    DRAGON: { bg: "bg-purple-700", text: "text-white" },
    FAIRY: { bg: "bg-pink-400", text: "text-white" },
    DARK: { bg: "bg-gray-700", text: "text-white" },
    FIRE: { bg: "bg-orange-500", text: "text-white" },
    ICE: { bg: "bg-cyan-400", text: "text-gray-900" },
    FIGHTING: { bg: "bg-red-600", text: "text-white" },
    STEEL: { bg: "bg-slate-400", text: "text-white" },
};

export const newsArticles = [
    {
        id: 1,
        title: "New Discovery: IRON LLAVES",
        category: "IT",
        type: "GRASS",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1001.png",
        author: "Professor Ore",
        content:
            "Iron Llaves is a Paradox Pokémon discovered deep within Area Zero. This mechanical creature resembles ancient depictions found in a mysterious book. It has been classified as a Grass/Fighting type with remarkable endurance and power. This Pokémon is primarily classified as a grass type.",
        likes: 5,
        relatedIds: [5, 9],
    },
    {
        id: 2,
        title: "New Discovery: WALKING WAKE",
        category: "Finance",
        type: "WATER",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1009.png",
        author: "Professor Sada",
        content:
            "Walking Wake appears to be a Paradox Pokémon resembling Suicune. This ancient Water/Dragon type was first spotted near crystalline lakes in Area Zero. Researchers have marveled at its fluid movements and incredible speed on water surfaces.",
        likes: 8,
        relatedIds: [4, 3],
    },
    {
        id: 3,
        title: "New Discovery: MIRAIDON",
        category: "IT",
        type: "ELECTRIC",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1007.png",
        author: "Professor Ore",
        content:
            "Miraidon is a legendary Pokémon classified as Electric/Dragon type. It appears to be a futuristic creature that can harness electromagnetic energy. Scientific analysis reveals a possible weight of 240kg. This Pokémon is primarily classified as an electric type.",
        likes: 3,
        relatedIds: [1, 5],
    },
    {
        id: 4,
        title: "New Discovery: ROARING MOON",
        category: "Culture",
        type: "DRAGON",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1005.png",
        author: "Professor Sada",
        content:
            "Roaring Moon appears to be a Paradox Pokémon resembling Salamence. This ancient Dragon/Dark type creature has extraordinary strength and wingspan found in the deepest parts of Area Zero.",
        likes: 12,
        relatedIds: [2, 8],
    },
    {
        id: 5,
        title: "New Discovery: IRON VALIANT",
        category: "HR",
        type: "FAIRY",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1006.png",
        author: "Professor Ore",
        content:
            "Iron Valiant is a Paradox Pokémon with a resemblance to both Gallade and Gardevoir. This futuristic Fairy/Fighting type is highly aggressive and battles with extraordinary precision using its blade-like arms.",
        likes: 7,
        relatedIds: [1, 3],
    },
    {
        id: 6,
        title: "New Discovery: CHI-YU",
        category: "HSE",
        type: "DARK",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1004.png",
        author: "Professor Sada",
        content:
            "Chi-Yu is one of the Treasures of Ruin Pokémon. This Fire/Dark type was sealed away long ago due to its dangerous power that could set the entire world ablaze with malicious intent.",
        likes: 4,
        relatedIds: [7, 8],
    },
    {
        id: 7,
        title: "New Discovery: TING-LU",
        category: "Facilities",
        type: "DARK",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1002.png",
        author: "Professor Sada",
        content:
            "Ting-Lu is one of the Treasures of Ruin Pokémon. This Ground/Dark type massive creature carries an ancient urn on its head and can cause earthquakes with each powerful step it takes.",
        likes: 6,
        relatedIds: [6, 8],
    },
    {
        id: 8,
        title: "New Discovery: CHIEN-PAO",
        category: "Finance",
        type: "DARK",
        isNew: true,
        date: "Apr 4, 2025",
        readTime: "3 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1003.png",
        author: "Professor Ore",
        content:
            "Chien-Pao is one of the Treasures of Ruin Pokémon. This Ice/Dark type wields ice blades like swords and can freeze anything it touches. It was sealed by an ancient hero long ago.",
        likes: 9,
        relatedIds: [6, 7],
    },
    {
        id: 9,
        title: "New Discovery: IRON TREADS",
        category: "IT",
        type: "STEEL",
        isNew: false,
        date: "Apr 3, 2025",
        readTime: "2 min",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1008.png",
        author: "Professor Ore",
        content:
            "Iron Treads appears to be a Paradox Pokémon resembling Donphan. This futuristic Ground/Steel type has wheels instead of legs and can roll at incredible speeds across any terrain.",
        likes: 11,
        relatedIds: [1, 5],
    },
];
